export const getTopPOIs = () => {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve([
        {
          rank: 1,
          name: "The Pastel Bistro",
          location: "London, UK",
          lat: 51.5074,
          lng: -0.1278,
          category: "Museum",
          priority: "CRITICAL",
          status: "PENDING",
          listens: 2450,
          percent: 95,
        },
        {
          rank: 2,
          name: "Royal Art Gallery",
          location: "New York, USA",
          lat: 40.7128,
          lng: -74.006,
          category: "Museum",
          priority: "MEDIUM",
          status: "APPROVED",
          listens: 1920,
          percent: 78,
        },
        {
          rank: 3,
          name: "Midnight Brews",
          location: "Tokyo, Japan",
          lat: 35.6762,
          lng: 139.6503,
          priority: "HIGH",
          status: "PENDING",
          category: "Cafe",
          listens: 1810,
          percent: 65,
        },
          {
          rank: 4,
          name: "Sunset Terrace",
          location: "Cliff Edge",
          lat: 35.6762,
          lng: 139.6503,
          priority: "HIGH",
          status: "PENDING",
          category: "Cafe",
          listens: 1500,
          percent: 55,
        },
        {
          rank: 5,
          name: "Heritage Walk",
          location: "Old Quarter",
          lat: 35.6762,
          lng: 139.6503,
          priority: "HIGH",
          status: "PENDING",
          category: "Restaurant",
          listens: 1400,
          percent: 50,
        },
        {
          rank: 6,
          name: "Neon Arcade",
          location: "Downtown",
          lat: 35.6762,
          lng: 139.6503,
          priority: "HIGH",
          status: "PENDING",
          category: "Restaurant",
          listens: 1300,
          percent: 45,
        },
        {
          rank: 7,
          name: "City Library",
          location: "Culture Hub",
          lat: 35.6762,
          lng: 139.6503,
          priority: "HIGH",
          status: "PENDING",
          category: "Restaurant",
          listens: 1200,
          percent: 40,
        },
      ])
    }, 800)
  })
}