@Server_HostAddress = http://localhost:5086

GET {{Server_HostAddress}}/weatherforecast/
Accept: application/json

### Setup admin account
# POST {{Server_HostAddress}}/api/auth/setup-dev
# Content-Type: application/json

# {
#   "username": "admin",
#   "password": "Admin@123"
# }

### Login
# POST {{Server_HostAddress}}/api/auth/login
# Content-Type: application/json

# {
#   "username": "admin",
#   "password": "Admin@123"
# }

#GET {{Server_HostAddress}}/api/cms/pois
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjRhOTgzYWI2LWNkMDUtNGMyZC05MDdiLTUzNWZiODg1ZDg1MiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJhZG1pbiIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNzc1NzEwNDk4LCJpc3MiOiJBdWRpb0dvQXBpIiwiYXVkIjoiQXVkaW9Hb0NsaWVudHMifQ.5D8R7je95kN_CkvNh1ujZLTc3A6pOySyFNAlo6kChZw

### Create POI
# POST {{Server_HostAddress}}/api/cms/pois
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjRhOTgzYWI2LWNkMDUtNGMyZC05MDdiLTUzNWZiODg1ZDg1MiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJhZG1pbiIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNzc1NzEwNDk4LCJpc3MiOiJBdWRpb0dvQXBpIiwiYXVkIjoiQXVkaW9Hb0NsaWVudHMifQ.5D8R7je95kN_CkvNh1ujZLTc3A6pOySyFNAlo6kChZw

# {
#   "latitude": 10.762622,
#   "longitude": 106.660172,
#   "activationRadius": 50,
#   "priority": 1,
#   "status": "Draft",
#   "logoUrl": "https://example.com/logo.png"
# }

GET {{Server_HostAddress}}/api/cms/acc-admin-001/pois
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjBlMjQ4NjA3LTE3NWItNGNhZi1iOTc4LTZlZGY2ZGY2YjFkOSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJhZG1pbiIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNzc1ODA0ODQ3LCJpc3MiOiJBdWRpb0dvQXBpIiwiYXVkIjoiQXVkaW9Hb0NsaWVudHMifQ.5YogWPOYDv4GHZbxHbrCZkQ8NSj8pf-O1WT0LI2YkQs

###GET {{Server_HostAddress}}/api/cms/pois/cb1acbbd-96cc-4530-a410-5396639257bf
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjRhOTgzYWI2LWNkMDUtNGMyZC05MDdiLTUzNWZiODg1ZDg1MiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJhZG1pbiIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNzc1NzEwNDk4LCJpc3MiOiJBdWRpb0dvQXBpIiwiYXVkIjoiQXVkaW9Hb0NsaWVudHMifQ.5D8R7je95kN_CkvNh1ujZLTc3A6pOySyFNAlo6kChZw

#GET {{Server_HostAddress}}/api/cms/accounts
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjRhOTgzYWI2LWNkMDUtNGMyZC05MDdiLTUzNWZiODg1ZDg1MiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJhZG1pbiIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNzc1NzEwNDk4LCJpc3MiOiJBdWRpb0dvQXBpIiwiYXVkIjoiQXVkaW9Hb0NsaWVudHMifQ.5D8R7je95kN_CkvNh1ujZLTc3A6pOySyFNAlo6kChZw


###
